var = {'tracks': {
    'href': 'https://api.spotify.com/v1/search?query=My+Heart+Will+Go+On&type=track&market=CA&offset=0&limit=1',
    'items': [{'album': {'album_type': 'album',
                         'artists': [{'external_urls': {
                             'spotify': 'https://open.spotify.com/artist/4S9EykWXhStSc15wEx8QFK'},
                             'href': 'https://api.spotify.com/v1/artists/4S9EykWXhStSc15wEx8QFK',
                             'id': '4S9EykWXhStSc15wEx8QFK',
                             'name': 'Céline '
                                     'Dion',
                             'type': 'artist',
                             'uri': 'spotify:artist:4S9EykWXhStSc15wEx8QFK'}],
                         'external_urls': {'spotify': 'https://open.spotify.com/album/1tfS7Fo1UtAxQSf256fnYs'},
                         'href': 'https://api.spotify.com/v1/albums/1tfS7Fo1UtAxQSf256fnYs',
                         'id': '1tfS7Fo1UtAxQSf256fnYs',
                         'images': [{'height': 640,
                                     'url': 'https://i.scdn.co/image/ab67616d0000b273745adc3f697ea1ec79d66901',
                                     'width': 640},
                                    {'height': 300,
                                     'url': 'https://i.scdn.co/image/ab67616d00001e02745adc3f697ea1ec79d66901',
                                     'width': 300},
                                    {'height': 64,
                                     'url': 'https://i.scdn.co/image/ab67616d00004851745adc3f697ea1ec79d66901',
                                     'width': 64}],
                         'is_playable': True,
                         'name': "Let's Talk About Love",
                         'release_date': '1997-11-14',
                         'release_date_precision': 'day',
                         'total_tracks': 16,
                         'type': 'album',
                         'uri': 'spotify:album:1tfS7Fo1UtAxQSf256fnYs'},
               'artists': [
                   {'external_urls': {'spotify': 'https://open.spotify.com/artist/4S9EykWXhStSc15wEx8QFK'},
                    'href': 'https://api.spotify.com/v1/artists/4S9EykWXhStSc15wEx8QFK',
                    'id': '4S9EykWXhStSc15wEx8QFK',
                    'name': 'Céline Dion',
                    'type': 'artist',
                    'uri': 'spotify:artist:4S9EykWXhStSc15wEx8QFK'}],
               'disc_number': 1,
               'duration_ms': 280000,
               'explicit': False,
               'external_ids': {'isrc': 'CAC229700120'},
               'external_urls': {'spotify': 'https://open.spotify.com/track/33LC84JgLvK2KuW43MfaNq'},
               'href': 'https://api.spotify.com/v1/tracks/33LC84JgLvK2KuW43MfaNq',
               'id': '33LC84JgLvK2KuW43MfaNq',
               'is_local': False,
               'is_playable': True,
               'name': 'My Heart Will Go On - Love Theme '
                       'from "Titanic"',
               'popularity': 77,
               'preview_url': 'https://p.scdn.co/mp3-preview/68c13229ec9b1b4a5ea580e801061fd7791857c4?cid=e09e23c9ab82431a864f090d5d66f1d2',
               'track_number': 12,
               'type': 'track',
               'uri': 'spotify:track:33LC84JgLvK2KuW43MfaNq'}],
    'limit': 1,
    'next': 'https://api.spotify.com/v1/search?query=My+Heart+Will+Go+On&type=track&market=CA&offset=1&limit=1',
    'offset': 0,
    'previous': None,
    'total': 802}}
