var = {'status': 'ok', 'totalResults': 19, 'articles': [
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': 'Watch: Tesla Model Y Takes A Pounding In German Hailstorm, Gets Mixed Reaction',
     'description': 'A black Tesla Inc TSLA Model Y was seemingly damaged by a hailstorm in Germany over the past weekend. What Happened: The video of the vehicle caught in the hailstorm was posted on X, formerly Twitter, by Drive Tesla Canada, a news website dedicated to Tesla u…',
     'url': 'https://biztoc.com/x/7f20dd938ff85ba5', 'urlToImage': 'https://c.biztoc.com/p/7f20dd938ff85ba5/s.webp',
     'publishedAt': '2023-08-30T11:52:03Z',
     'content': 'A black Tesla Inc TSLA Model Y was seemingly damaged by a hailstorm in Germany over the past weekend.What Happened: The video of the vehicle caught in the hailstorm was posted on X, formerly Twitter,… [+295 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': 'Tesla CEO Elon Musk Reiterates Continued Dependence On Both Nvidia And Dojo For AI Processing',
     'description': "Tesla Inc TSLA CEO Elon Musk on Monday said that the EV giant will continue to rely on chip-maker Nvidia Corp NVDA. What Happened: “We're going with both Dojo and Nvidia,” Musk said. He was responding to an X.com user who wondered if Tesla would pull a page f…",
     'url': 'https://biztoc.com/x/8e872284d7e8b3fb', 'urlToImage': 'https://c.biztoc.com/p/8e872284d7e8b3fb/s.webp',
     'publishedAt': '2023-08-29T03:54:04Z',
     'content': "Tesla Inc TSLA CEO Elon Musk on Monday said that the EV giant will continue to rely on chip-maker Nvidia Corp NVDA.What Happened: We're going with both Dojo and Nvidia, Musk said. He was responding t… [+290 chars]"},
    {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'Upwallstreet',
     'title': 'The Acceleration Of The EV Revolution Comes With Business Expansion',
     'description': 'Although Tesla Inc (NASDAQ: TSLA) helped create the EV industry, both in the U.S. and China, it is now facing intense competition on both fronts. Fighting...',
     'url': 'https://finance.yahoo.com/news/acceleration-ev-revolution-comes-business-173836304.html',
     'urlToImage': 'https://media.zenfs.com/en/Benzinga/14ac6fcf500c399cedabe9f372891de9',
     'publishedAt': '2023-08-30T17:38:36Z',
     'content': 'Although Tesla Inc (NASDAQ: TSLA) helped create the EV industry, both in the U.S. and China, it is now facing intense competition on both fronts. Fighting for market share, Tesla started a price war … [+5752 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Elon Musk Says Tesla's Software Is Like Apple's, You Can't Just Copy It",
     'description': 'Tesla Inc TSLA CEO Elon Musk, on Monday, drew a parallel between the EV giant’s software and that of tech giant Apple Inc AAPL. What Happened: One cannot just copy the code of Tesla software, Musk said. The CEO describes this as a perk of having one’s own har…',
     'url': 'https://biztoc.com/x/d633a51f5766d699', 'urlToImage': 'https://c.biztoc.com/p/d633a51f5766d699/s.webp',
     'publishedAt': '2023-08-29T08:34:05Z',
     'content': 'Tesla Inc TSLA CEO Elon Musk, on Monday, drew a parallel between the EV giants software and that of tech giant Apple Inc AAPL.What Happened: One cannot just copy the code of Tesla software, Musk said… [+276 chars]'},
    {'source': {'id': None, 'name': 'MarketWatch'}, 'author': 'Claudia Assis',
     'title': ': Tesla’s stock rises the most in five months',
     'description': 'Shares of Tesla Inc. TSLA on Tuesday ended at their highest in nearly three weeks and notched their largest one-day percentage increase since March 21, when the shares rose 7.82%. The EV maker’s stock still holds to a 3% decline so far in August, compared wit…',
     'url': 'https://www.marketwatch.com/story/teslas-stock-rises-the-most-in-five-months-b7609760',
     'urlToImage': 'https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg',
     'publishedAt': '2023-08-29T20:44:00Z',
     'content': 'Shares of Tesla Inc. \r\n TSLA,\r\n +7.69%\r\non Tuesday ended at their highest in nearly three weeks and notched their largest one-day percentage increase since March 21, when the shares rose 7.82%. The E… [+358 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Musk Responds To Hertz's Tesla Rental Practices After Customer Complains Of Missing Chargers",
     'description': 'On Tuesday, Tesla Inc TSLA CEO Elon Musk said that the EV giant will look into how its vehicles are being rented by car rental company Hertz Global Holdings Inc HTZ. “We will look into this,” Musk said. The CEO was responding to a user who recounted his exper…',
     'url': 'https://biztoc.com/x/d0ede74a6c7a2983', 'urlToImage': 'https://c.biztoc.com/p/d0ede74a6c7a2983/s.webp',
     'publishedAt': '2023-08-29T11:36:03Z',
     'content': 'On Tuesday, Tesla Inc TSLA CEO Elon Musk said that the EV giant will look into how its vehicles are being rented by car rental company Hertz Global Holdings Inc HTZ.We will look into this, Musk said.… [+294 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': 'Tesla Rolls Out FSD Beta For Vehicles Equipped With Hardware 4, A Day After Musk Warns 6-Month Delay',
     'description': 'Tesla Inc TSLA has seemingly rolled out its full self-driving (FSD) software for Tesla vehicles equipped with hardware 4. The move comes a day after CEO Elon Musk warned that FSD on hardware 4 will lag hardware 3 by at least another six months. What Happened:…',
     'url': 'https://biztoc.com/x/23601f249a526261', 'urlToImage': 'https://c.biztoc.com/p/23601f249a526261/s.webp',
     'publishedAt': '2023-08-29T06:28:04Z',
     'content': 'Tesla Inc TSLA has seemingly rolled out its full self-driving (FSD) software for Tesla vehicles equipped with hardware 4. The move comes a day after CEO Elon Musk warned that FSD on hardware 4 will l… [+267 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': 'Musk May Soon Launch App For Tesla To Watch Latest From X',
     'description': 'Elon Musk’s announcement of an upcoming Twitter, now rebranded as X, app for Tesla Inc. TSLA vehicles has ignited excitement and concern, as the prospect of in-car X video viewing raises serious questions about distracted driving. What Happened: Musk made wav…',
     'url': 'https://biztoc.com/x/5288eed5a947ca1e', 'urlToImage': 'https://c.biztoc.com/p/5288eed5a947ca1e/s.webp',
     'publishedAt': '2023-08-29T08:34:06Z',
     'content': 'Elon Musks announcement of an upcoming Twitter, now rebranded as X, app for Tesla Inc. TSLA vehicles has ignited excitement and concern, as the prospect of in-car X video viewing raises serious quest… [+270 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Is Nvidia's H100 AI Chip Worth The Hype? Musk Reveals Effects On Tesla's FSD Testing",
     'description': 'This week, Tesla, Inc. TSLA made a significant move by activating a 10,000-unit Nvidia Corp. (NVDA) H100 GPU cluster to accelerate the training of its full self-driving technology. Elon Musk, the CEO of the electric vehicle company, also weighed in on the chi…',
     'url': 'https://biztoc.com/x/47038c279b207cf5', 'urlToImage': 'https://c.biztoc.com/p/47038c279b207cf5/s.webp',
     'publishedAt': '2023-08-30T08:36:03Z',
     'content': 'This week, Tesla, Inc. TSLA made a significant move by activating a 10,000-unit Nvidia Corp. (NVDA) H100 GPU cluster to accelerate the training of its full self-driving technology. Elon Musk, the CEO… [+264 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Elon Musk's Tesla Autopilot Faces Scrutiny As US Safety Regulator Questions 'Driver Inattention' Risk",
     'description': 'In a move that intensifies scrutiny on Elon Musk’s Tesla Inc. TSLA, the U.S. auto safety regulator has demanded an explanation on a software change in the company’s Autopilot driver assistance system, Reuters reported. In a recently revealed letter, the Natio…',
     'url': 'https://biztoc.com/x/73ed6ecea9d0f1bd', 'urlToImage': 'https://c.biztoc.com/p/73ed6ecea9d0f1bd/s.webp',
     'publishedAt': '2023-08-30T04:10:03Z',
     'content': 'In a move that intensifies scrutiny on Elon Musks Tesla Inc. TSLA, the U.S. auto safety regulator has demanded an explanation on a software change in the companys Autopilot driver assistance system, … [+270 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': '247wallst.com', 'title': 'Tesla’s Only Challenger',
     'description': 'Chinese automaker BYD sold 700,244 vehicles in the second quarter. Tesla Inc. (NASDAQ: TSLA) delivered 466,140 for the same period. Granted, BYD is not a global company. By the same token, China is the world’s largest car market by far. (These are the 13 bigg…',
     'url': 'https://biztoc.com/x/8325b132b28afe45', 'urlToImage': 'https://c.biztoc.com/p/8325b132b28afe45/s.webp',
     'publishedAt': '2023-08-29T15:38:04Z',
     'content': 'Chinese automaker BYD sold 700,244 vehicles in the second quarter. Tesla Inc. (NASDAQ: TSLA) delivered 466,140 for the same period. Granted, BYD is not a global company. By the same token, China is t… [+292 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "What Ignited Tesla's Electrifying Tuesday Rally? Analyst Spotlights 2 Key Catalysts Behind Surge",
     'description': 'Tesla, Inc. TSLA surged ahead on Tuesday, overshadowing other mega-cap stocks, and Gary Black of Future Fund examined the factors underpinning this remarkable performance. The Impetus: Tesla’s stock gained traction from Tuesday’s Job Openings and Labor Turnov…',
     'url': 'https://biztoc.com/x/411d8dc917f1bc45', 'urlToImage': 'https://c.biztoc.com/p/411d8dc917f1bc45/s.webp',
     'publishedAt': '2023-08-30T06:16:04Z',
     'content': 'Tesla, Inc. TSLA surged ahead on Tuesday, overshadowing other mega-cap stocks, and Gary Black of Future Fund examined the factors underpinning this remarkable performance.The Impetus: Teslas stock ga… [+307 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Musk Isn't Throwing Stones, But Tesla Under DOJ And SEC Investigation Over 'Glass House' Project",
     'description': 'Elon Musk’s Tesla Inc TSLA is once again under the scrutiny of federal agencies — the Department of Justice (DOJ) and the Securities and Exchange Commission (SEC) — over a secretive initiative known as “Project 42.” The investigations focus on the potential m…',
     'url': 'https://biztoc.com/x/c56ba98c909e0c31', 'urlToImage': 'https://c.biztoc.com/p/c56ba98c909e0c31/s.webp',
     'publishedAt': '2023-08-30T21:42:10Z',
     'content': 'Elon Musks Tesla Inc TSLA is once again under the scrutiny of federal agencies the Department of Justice (DOJ) and the Securities and Exchange Commission (SEC) over a secretive initiative known as Pr… [+276 chars]'},
    {'source': {'id': None, 'name': 'Marketscreener.com'}, 'author': 'PRNewswire',
     'title': 'Thinking about trading options or stock in Tesla, Microsoft, PDD Holdings, Coinbase Global, or Amazon.com?',
     'description': '(marketscreener.com) \n\nNEW YORK, Aug. 29, 2023 /PRNewswire/ -- InvestorsObserver issues critical PriceWatch Alerts for TSLA, MSFT, PDD, COIN, and AMZN.\n\n \n \n \n \n \n \n\n \nClick a link below then choose between in-depth options trade idea report or a stock score.…',
     'url': 'https://www.marketscreener.com/quote/stock/PINDUODUO-INC-45049866/news/Thinking-about-trading-options-or-stock-in-Tesla-Microsoft-PDD-Holdings-Coinbase-Global-or-Amazo-44722006/',
     'urlToImage': 'https://www.marketscreener.com/images/twitter_MS_fdnoir.png', 'publishedAt': '2023-08-29T13:32:05Z',
     'content': 'NEW YORK, Aug. 29, 2023 /PRNewswire/ -- InvestorsObserver issues critical PriceWatch Alerts for TSLA, MSFT, PDD, COIN, and AMZN.\r\nClick a link below then choose between in-depth options trade idea re… [+1560 chars]'},
    {'source': {'id': None, 'name': 'Biztoc.com'}, 'author': 'benzinga.com',
     'title': "Elon Musk Doesn't 'Hate' LiDAR, Says It's Good For Space Vehicles",
     'description': 'Tesla Inc TSLA CEO Elon Musk on Monday reiterated his criticism of LiDAR technology on roads. What Happened: The CEO said that he did his best to warn people that LiDAR isn’t ideal for cars. “Roads are designed for biological neural nets & eyes, so digital ne…',
     'url': 'https://biztoc.com/x/9ca09517477064ad', 'urlToImage': 'https://c.biztoc.com/p/9ca09517477064ad/s.webp',
     'publishedAt': '2023-08-29T05:32:03Z',
     'content': 'Tesla Inc TSLA CEO Elon Musk on Monday reiterated his criticism of LiDAR technology on roads.What Happened: The CEO said that he did his best to warn people that LiDAR isnt ideal for cars. Roads are … [+279 chars]'},
    {'source': {'id': None, 'name': 'MarketWatch'}, 'author': 'Jon Swartz',
     'title': ': Altman, Zuckerberg headline Sen. Schumer’s Who’s Who list for AI summit in September',
     'description': 'OpenAI’s Sam Altman, Mark Zuckerberg of Meta Platforms Inc. META , Tesla Inc.’s TSLA Elon Musk, Microsoft Corp.’s MSFT Satya Nadella, and Alphabet Inc.’s GOOGLGOOG Sundar Pichai head the list of chief executives scheduled to meet Senate Majority Leader Chuck …',
     'url': 'https://www.marketwatch.com/story/altman-zuckerberg-headline-sen-schumers-whos-who-list-for-ai-summit-in-september-79dfc59b',
     'urlToImage': 'https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg',
     'publishedAt': '2023-08-30T21:37:29Z',
     'content': 'OpenAIs Sam Altman, Mark Zuckerberg of Meta Platforms Inc. \r\n META,\r\n -0.97%\r\n,\r\n Tesla Inc.s \r\n TSLA,\r\n -0.11%\r\nElon Musk, Microsoft Corp.s \r\n MSFT,\r\n +0.12%\r\nSatya Nadella, and Alphabet Inc.s \r\n GO… [+327 chars]'},
    {'source': {'id': None, 'name': 'MarketWatch'}, 'author': 'Tomi Kilgore',
     'title': ': Tesla stock pulls back, after S&P 500-leading rally in previous session',
     'description': 'Shares of Tesla Inc. TSLA pulled back 0.6% in premarket trading Wednesday, after charging up 7.7% to pace the S&P 500’s SPX gainers in the previous session. The electric vehicle giant’s stock, which closed Tuesday at a four-week high, has rallied 11.8% amid a…',
     'url': 'https://www.marketwatch.com/story/tesla-stock-pulls-back-after-s-p-500-leading-rally-in-previous-session-15bafdc2',
     'urlToImage': 'https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg',
     'publishedAt': '2023-08-30T11:22:25Z',
     'content': 'Shares of Tesla Inc. \r\n TSLA,\r\n +7.69%\r\npulled back 0.6% in premarket trading Wednesday, after charging up 7.7% to pace the S&amp;P 500s \r\n SPX,\r\n +1.45%\r\ngainers in the previous session. The electri… [+603 chars]'},
    {'source': {'id': None, 'name': 'MarketWatch'}, 'author': 'Claudia Assis',
     'title': ': Elon Musk’s ‘glass house’ under investigation: WSJ',
     'description': 'Federal prosecutors are investigating the use of Tesla Inc. TSLA funds on a “secret” project thought to be a house for Chief Executive Elon Musk, the Wall Street Journal reported Wednesday, citing people familiar with the matter. The U.S. Attorney’s Office fo…',
     'url': 'https://www.marketwatch.com/story/elon-musks-glass-house-under-investigation-wsj-d3dca69',
     'urlToImage': 'https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg',
     'publishedAt': '2023-08-30T20:08:04Z',
     'content': 'Federal prosecutors are investigating the use of Tesla Inc. \r\n TSLA,\r\n -0.11%\r\nfunds on a secret project thought to be a house for Chief Executive Elon Musk, the Wall Street Journal reported Wednesda… [+567 chars]'},
    {'source': {'id': None, 'name': 'MarketWatch'}, 'author': 'Wallace Witkowski',
     'title': ': Nvidia’s stock on track for record closing high, $1.2 trillion market cap',
     'description': 'Nvidia Corp. NVDA shares were on track to resume their year-to-date push higher Tuesday, as the stock eyed its first new record closing high in more than a month. Nvidia shares rallied nearly 5% Tuesday to an intraday high of $490.81, while the S&P 500 index …',
     'url': 'https://www.marketwatch.com/story/nvidias-stock-on-track-for-record-closing-high-1-2-trillion-market-cap-961429c1',
     'urlToImage': 'https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg',
     'publishedAt': '2023-08-29T18:21:32Z',
     'content': 'Nvidia Corp. \r\n NVDA,\r\n +4.51%\r\nshares were on track to resume their year-to-date push higher Tuesday, as the stock eyed its first new record closing high in more than a month. Nvidia shares rallied … [+1290 chars]'}]}
